theme: hugo-profile
title: 前端问答社
enableGitInfo: true
outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
services:
  googleAnalytics:
    ID: G-7FEY3L54XY
# defaultContentLanguage: zh
# languages:
#   zh:
#     languageName: 中文
#     languageCode: zh-CN
#     contentDir: content/zh
#     title:
#     params:
#       disabled: false
#       title: 前端问答社
#
#     weight: 2
params:
  description: 一个分享web前端知识博客
  # staticPath: ""  # The path to serve the static files from
  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false
  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: true # Show brand logo in nav bar | default is true
    brandName: "前端问答社" # Brand name for the brand | default is the title variable
    disableSearch: false
    searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableProjects: false
      disableContact: false

      disableExperience: true
      disableEducation: true
      disableAchievements: true
      disableDocument: true
  # Hero
  hero:
    enable: true
    intro: "Hi,My Name is "
    title: "Jabin He."
    subtitle: "享受安静地写自己喜欢的东西，顺便分享一些知识！"
    content: "一个对web开发充满热情与激情的人，经常捣鼓一些突发奇想的项目。"
    image: /images/hero.svg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "浏览我的项目"
      url: "/projects"
      download: false
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/anderlaw
        - icon: fab fa-twitter
          url: https://twitter.com/JabinDev
      #自定义icon
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  footer:
    # recentPosts:
    #   path: "posts"
    #   count: 100
    #   title: Recent Posts
    #   enable: true
    #   disableFeaturedImage: false
    # socialNetworks:
    #   github: https://github.com
    #   linkedin: https://linkedin.com
    #   twitter: https://twitter.com
    #   instagram: https://instagram.com
    #   facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
  favicon: /favicon2.ico
  author:
    name: Your Name
    url: https://your.site

  themeColors:
    light: "#ffffff"
    dark: "#121212"

  years:
    start: ""
    present: 2023

  social:
    github: ""
    youtube: ""
    facebook: ""
    x: ""

  ads:
    googleAdSense: ""

  donate:
    buyMeACoffee: ""
    githubSponsor: ""

  algolia:
    en:
      container: "#site-header-search"
      appId: ""
      indexName: ""
      apiKey: ""

  home:
    repository: "your/repo"

menu:
  main:
    # 未启用这里的菜单
    - url: /
      name: Home
      identifier: home
      pre: "<i class='icon icon-home'></i>"
      weight: 1
